### ISSUE TITLE
Difficultés pour driver le display recommandé

### ISSUE THREAD

**Issue by jmMeessen** [breizhcamp/LikeBox#4]
J'ai commendé le display 20 x 4 recommandé pour essayer de reproduire une partie du montage. J'ai du mal à le faire fonctionner. J'ai utilisé diverses librairies python mais sans succès. Le display est bien détecté sur le bus I2C et je sais allumer/éteindre le backlight. Cela me fait penser que ma connectique est bonne mais que la configuration n'est pas correcte pour commander correctement le display via le I2C extender du display.
Auriez vous des conseils/pistes à me donner ?

**Comment by srevereault** [comment]
Quelques pistes : 
- vérifier que les i2c-tools sont bien installés
- vérifier que le driver i2c est bien activé (voir http://raspberrypi.stackexchange.com/questions/29820/cant-activate-i2c-on-my-b par exemple)
- essayer avec le code de la Likebox client en mode debug (voir https://github.com/breizhcamp/LikeBox/blob/master/client/README.md )

**Comment by lhuet** [comment]
A priori, si une commande i2c permet d'allumer/éteindre le backlight, il est fort probable que la communication i2c soit correcte.
Ça me rappelle plutôt un truc tout bête du genre le potard de contraste mis au mini (il doit être facilement accessible au dos du LCD 20x4 avec une vis en forme de croix si mes souvenirs sont bons). Ça m'est arrivé et j'ai cherché un peu avant de comprendre ce qu'il se passait !

**Comment by jmMeessen** [comment]
merci pour les tuyaux. Je dois attendre ce soir pour confirmer.

J'ai l'intuition que c'est le potard de contraste qui est la cause de mes frustrations. Si c'est cela, je vous apporterai des chokotoffs au breizhcamp (en espérant que cela se goupille comme je pense). Ce règlage ne me serait jamais venu à l'esprit.

**Comment by jmMeessen** [comment]
Bingo !
C'est bien le potard !
